In [1]:
import h5py
import numpy as np
from timeit import timeit

In [2]:
# Specification for file use
file_path = '/Users/franciscosargo/hdf5_experiments/'
file_name = 'store_h5py.h5'
full_path = file_path + file_name

In [3]:
# Create dummy array

# Specify metadata
patient = 'Patient1'
seizure = 'seizure_0'
Fs = 1000
delta_t = 200 # time in seconds
initial_t = 0 # initial time in seconds
features = ['1', '2', '3', '4', '5'] # specify number of features

# Create array
data_sz_pt_np = np.random.rand(delta_t * Fs, len(features))

In [4]:
data_sz_pt_np

array([[ 0.18512694,  0.01666633,  0.99878325,  0.56323918,  0.44404045],
       [ 0.74903658,  0.25563573,  0.28598149,  0.88942905,  0.01065773],
       [ 0.79657236,  0.3391643 ,  0.47925568,  0.00430949,  0.61652058],
       ..., 
       [ 0.44613569,  0.5621301 ,  0.32600227,  0.72064615,  0.78956731],
       [ 0.94361312,  0.64989508,  0.45749313,  0.6893964 ,  0.5322609 ],
       [ 0.84714555,  0.3131499 ,  0.13545898,  0.91716164,  0.90000128]])

In [6]:
# save data and load it
print data_sz_pt_np.dtype

# save original type
name = '64.h5'
with h5py.File(file_path + name, 'w') as f:
    f['new_data'] = data_sz_pt_np
    
# save original type
name = '32.h5'
with h5py.File(file_path + name, 'w') as f:
    f.create_dataset('new_data', data=data_sz_pt_np,
                     dtype=np.float32)
    dset = f['new_data']
    np_data = dset[:]
    np_data_2 = dset[...]
    print type(dset)
    print type(np_data)
    print np_data
    print np_data_2

float64
<class 'h5py._hl.dataset.Dataset'>
<type 'numpy.ndarray'>
[[ 0.18512695  0.01666632  0.99878323  0.56323916  0.44404045]
 [ 0.74903655  0.25563574  0.28598148  0.88942903  0.01065773]
 [ 0.79657233  0.33916429  0.47925568  0.00430949  0.61652058]
 ..., 
 [ 0.4461357   0.56213009  0.32600227  0.72064614  0.78956729]
 [ 0.94361311  0.64989507  0.45749313  0.68939638  0.53226089]
 [ 0.84714556  0.3131499   0.13545898  0.91716164  0.90000129]]
[[ 0.18512695  0.01666632  0.99878323  0.56323916  0.44404045]
 [ 0.74903655  0.25563574  0.28598148  0.88942903  0.01065773]
 [ 0.79657233  0.33916429  0.47925568  0.00430949  0.61652058]
 ..., 
 [ 0.4461357   0.56213009  0.32600227  0.72064614  0.78956729]
 [ 0.94361311  0.64989507  0.45749313  0.68939638  0.53226089]
 [ 0.84714556  0.3131499   0.13545898  0.91716164  0.90000129]]
